Src/CSMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import csmedia_home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', csmedia_home_view, name='Home-Page'),
    path('CSMediaProfiles/', include('CSMediaProfiles.urls', namespace='CSMediaProfiles')),
    path('CSMediaPosts/', include('CSMediaPosts.urls', namespace='CSMediaPosts')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Src/CSMediaPosts/urls.py
from django.urls import path
from .views import csmedia_post_view, csmedia_like_unlike

app_name = 'CSMediaPosts'

urlpatterns = [
    path('', csmedia_post_view, name='Main-Post-Page'),
    path('liked/', csmedia_like_unlike, name='Like-Post-Page')

]

Src/CSMediaPosts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from CSMediaProfiles.models import CSMediaProfile

# Create your models here.

# Post model
class CSMediaPost(models.Model):
    post_content = models.TextField()
    post_image = models.ImageField(upload_to='CSMediaPosts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    post_likes = models.ManyToManyField(CSMediaProfile, blank=True, related_name='Likes')
    updated_time = models.DateTimeField(auto_now_add=True)
    created_time = models.DateTimeField(auto_now_add=True)
    post_author = models.ForeignKey(CSMediaProfile, on_delete=models.CASCADE, related_name='Posts')

    def __str__(self):
        return str(self.post_content[:20])
    
    def number_of_likes(self):
        return self.post_likes.all().count()
    
    def number_of_comments(self):
        return self.CSMediaComment_set.all().count()

    class Meta:
        ordering = ('-created_time',)

# Comment Model
class CSMediaComment(models.Model):
    csmedia_user = models.ForeignKey(CSMediaProfile, on_delete=models.CASCADE)
    csmedia_post = models.ForeignKey(CSMediaPost, on_delete=models.CASCADE)
    comment_body = models.TextField(max_length=350)
    updated_time = models.DateTimeField(auto_now_add=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)
    
CSMEDIALIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

# Like Model
class CSMediaLike(models.Model):
    csmedia_user = models.ForeignKey(CSMediaProfile, on_delete=models.CASCADE)
    csmedia_post = models.ForeignKey(CSMediaPost, on_delete=models.CASCADE)
    post_like = models.CharField(choices=CSMEDIALIKE_CHOICES, max_length=8)
    updated_time = models.DateTimeField(auto_now_add=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.csmedia_user}-{self.csmedia_post}-{self.post_like}"

Src/CSMediaPosts/forms.py
from django import forms
from .models import CSMediaPost, CSMediaComment

class CSMediaPostForm(forms.ModelForm):
    post_content = forms.CharField(widget=forms.Textarea(attrs={'rows':2})) #edit again
    class Meta:
        model = CSMediaPost
        fields = ('post_content', 'post_image')

class CSMediaCommentForm(forms.ModelForm):
    comment_body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Sending some love ...'}))
    class Meta:
        model = CSMediaComment
        fields = ('comment_body',)





   

Src/CSMediaPosts/views.py
from django.shortcuts import render, redirect
from .models import CSMediaPost, CSMediaLike
from CSMediaProfiles.models import CSMediaProfile
from .forms import CSMediaPostForm, CSMediaCommentForm

# Create your views here.

def csmedia_post_view(request):
    csmedia_queryset = CSMediaPost.objects.all()
    csmedia_profile = CSMediaProfile.objects.get(csmedia_user=request.user)

    # initialise post & comment form
    csmedia_post_form = CSMediaPostForm()
    csmedia_comment_form = CSMediaCommentForm()
    csmedia_add_post = False
    csm_profile = CSMediaProfile.objects.get(csmedia_user=request.user)

    if 'submit_post_form' in request.POST:
        print(request.POST)

        csmedia_post_form = CSMediaPostForm(request.POST, request.FILES)
        if csmedia_post_form.is_valid():
            instance = csmedia_post_form.save(commit=False)
            instance.post_author = csm_profile 
            instance.save()
            csmedia_post_form = CSMediaPostForm()
            csmedia_add_post = True

    if 'submit_comment_form' in request.POST:
        csmedia_comment_form = CSMediaCommentForm(request.POST)
        if csmedia_comment_form.is_valid():
            instance = csmedia_comment_form.save(commit=False)
            instance.csmedia_user = csm_profile
            instance.csmedia_post = CSMediaPost.objects.get(id=request.POST.get('post_id'))
            instance.save()
            csmedia_comment_form = CSMediaCommentForm()
            csmediapost = CSMediaPost.objects.get(id=request.POST.get('post_id'))

    post_view_context = {
        'csmedia_queryset': csmedia_queryset,
        'csmedia_profile': csmedia_profile,
        'csmedia_post_form': csmedia_post_form,
        'csmedia_comment_form': csmedia_comment_form,
        'csmedia_add_post': csmedia_add_post,

    }

    return render(request, 'CSMediaPosts/main.html', post_view_context)

def csmedia_like_unlike(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get('post_id')
        post_object = CSMediaPost.objects.get(id=post_id)
        profile = CSMediaProfile.objects.get(csmedia_user=user)

        if profile in post_object.post_likes.all():
            post_object.post_likes.remove(profile)
        else:
            post_object.post_likes.add(profile)

        like, created = CSMediaLike.objects.get_or_create(csmedia_user=profile, csmedia_post_id=post_id)

        if not created:
            if like.post_like=='Like':
                like.post_like=='Unlike'
            else:
                like.post_like=='Like'
        else:
            like.post_like=='Like'
        
            post_object.save()
            like.save()

    return redirect('CSMediaPosts:Main-Post-Page')

    

Src/CSMediaPosts/templates/CSMediaPosts/main.html
<!--POST sDASHBOARD-->

{% extends 'base.html' %}

{% block title %}
    Main Page &hearts;
{% endblock title %}

{% block content %}
    <div class="ui grid modal-bottom csmedia-post-modal">
        <div class="row">
            <div class="twelve wide column">
                {% for posts in csmedia_queryset %}
                    <div class="ui fluid card">

                        <!--User Profile + Created Timestamp-->
                        <div class="content">
                            <div class="right floated meta">
                                <div class="ui grid">
                                    <!--Update & Delete Buttons not working yet ):-->
                                    <div class="row">
                                            <a href=""><button class="ui button">Update</button></a>
                                            <a href=""><button class="ui button">Delete</button></a>
                                    </div>
                                </div>
                            </div>

                            <img class="ui avatar image" src={{posts.post_author.user_avatar.url}}> 
                                {{posts.post_author.csmedia_user}}&nbsp;&hearts;&nbsp;&nbsp;&nbsp;&nbsp;{{posts.created_time|timesince}} ago
                        </div>

                        <!--Post Contents-->
                        <div class="ui fluid image">
                            {% if posts.image %}
                                <img src={{posts.image.url}}>
                            {% endif %}
                        </div>

                        <div class="content">
                            {{posts.post_content}}
                        </div>

                        <!--Likes Button + Number of Likes + Show comments-->
                        <div class="content">
                            <div class="right floated meta">
                                <div class="ui grid">
                                    <div class="row">
                                        <button class="csmedia-comment-button ui button">All Comments</button>
                                        <div class="csmedia-comment-box" style="display: none">
                                            {% if posts.csmediacomment_set.all %} 
                                                {% for comms in posts.csmediacomment_set.all %} 
                                                    <div class="ui segment">
                                                        <img class="ui avatar image" src={{comms.csmedia_user.user_avatar.url}}>
                                                            {{comms.csmedia_user}}
                                                        <div></div>
                                                        <div>{{comms.comment_body}}</div>
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <form action="{% url 'CSMediaPosts:Like-Post-Page' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{posts.id}}>
                                <button type="submit" class="ui button">
                                    {% if csmedia_profile in posts.post_likes.all %} 
                                        Give Hearts
                                    {% else %} 
                                        Take Hearts
                                    {% endif %} 
                                </button>                                        
                                &nbsp;{{posts.number_of_likes}}&nbsp;&hearts;
                            </form>
                        </div>

                        <!--Comments Section-->          
                        <div class="content">   
                                <form action="" method="POST" class="ui fluid form">
                                    {% csrf_token %} 
                                    <input type="hidden" name="post_id" value={{posts.id}}>
                                    {{csmedia_comment_form}}
                                    <button type="submit" class="ui button pink" name="submit_comment_form">Comment</button>                                                  
                                </form>
                        </div>               
                    </div>
                {% endfor %}
            </div>

            <div class="four wide column">
                <div class="ui segment">
                    {% if csmedia_add_post %} 
                        <div class="ui pink message">Yay! You have successfully added a post &hearts;</div>
                    {% endif %}
                    <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                        {% csrf_token %} 
                        {{csmedia_post_form}}
                    <button type="submit" class="ui button pink" name="submit_post_form">Post &hearts;</button>
                    </form>
                </div>
            </div>   
        </div>
    </div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        console.log('CSMedia is working! :)')

        let comment_display = false
                $(".csmedia-comment-button").click(function () {
                    if (comment_display===false) {
                        $(this).next(".csmedia-comment-box").show("slow");
                        comment_display=true
                    } else {
                        $(this).next(".csmedia-comment-box").hide("slow");
                        comment_display=false
                    }  
                });

    })
</script>
{% endblock scripts %}

.style.display = "none"